// Base local das estações de recarga GoodWe (dados de exemplo).
// Campos opcionais: "horario" = [abre, fecha] em horas (omitir = 24h) e "sessaoMediaMin".
// status: "disponivel" | "ocupado" | "manutencao"
const mockChargers = [
    {
        id: "gw-01",
        nome: "GoodWe Hub - Av. Paulista",
        lat: -23.56168,
        lng: -46.65613,
        potenciaKw: 150,
        tipo: "DC Fast",
        conectores: ["CCS2", "CHAdeMO"],
        vagasTotal: 4,
        vagasLivre: 3,
        precoKwh: 2.10,
        status: "disponivel"
    },
    {
        id: "gw-02",
        nome: "GoodWe Station - Marginal Pinheiros",
        lat: -23.60012,
        lng: -46.69722,
        potenciaKw: 60,
        tipo: "DC Fast",
        conectores: ["CCS2"],
        vagasTotal: 2,
        vagasLivre: 0,
        precoKwh: 1.95,
        status: "ocupado"
    },
    {
        id: "gw-03",
        nome: "GoodWe EcoCharge - Campinas Anhanguera",
        lat: -22.90511,
        lng: -47.05832,
        potenciaKw: 180,
        tipo: "Ultra Fast",
        conectores: ["CCS2", "Tipo 2"],
        vagasTotal: 6,
        vagasLivre: 4,
        precoKwh: 2.30,
        status: "disponivel"
    },
    {
        id: "gw-04",
        nome: "GoodWe Point - São José dos Campos (Dutra)",
        lat: -23.21852,
        lng: -45.89231,
        potenciaKw: 50,
        tipo: "DC",
        conectores: ["CCS2"],
        vagasTotal: 2,
        vagasLivre: 1,
        precoKwh: 1.85,
        status: "disponivel"
    },
    {
        id: "gw-05",
        nome: "GoodWe Hub - Rodovia dos Imigrantes",
        lat: -23.71212,
        lng: -46.57888,
        potenciaKw: 22,
        tipo: "AC Wallbox",
        conectores: ["Tipo 2"],
        vagasTotal: 2,
        vagasLivre: 0,
        precoKwh: 1.50,
        status: "manutencao"
    },
    {
        id: "gw-06",
        nome: "GoodWe Hub - Shopping Ibirapuera",
        lat: -23.61062,
        lng: -46.66788,
        potenciaKw: 75,
        tipo: "DC Fast",
        conectores: ["CCS2"],
        vagasTotal: 4,
        vagasLivre: 2,
        precoKwh: 2.05,
        status: "disponivel",
        horario: [10, 22]
    },
    {
        id: "gw-07",
        nome: "GoodWe Station - Aeroporto de Guarulhos",
        lat: -23.43555,
        lng: -46.47316,
        potenciaKw: 120,
        tipo: "DC Fast",
        conectores: ["CCS2", "CHAdeMO"],
        vagasTotal: 6,
        vagasLivre: 5,
        precoKwh: 2.25,
        status: "disponivel"
    },
    {
        id: "gw-08",
        nome: "GoodWe Point - Barueri (Castelo Branco)",
        lat: -23.5112,
        lng: -46.8765,
        potenciaKw: 50,
        tipo: "DC",
        conectores: ["CCS2"],
        vagasTotal: 3,
        vagasLivre: 1,
        precoKwh: 1.90,
        status: "disponivel"
    },
    {
        id: "gw-09",
        nome: "GoodWe EcoCharge - Sorocaba (Castelo Branco)",
        lat: -23.4938,
        lng: -47.4521,
        potenciaKw: 100,
        tipo: "DC Fast",
        conectores: ["CCS2"],
        vagasTotal: 4,
        vagasLivre: 2,
        precoKwh: 2.00,
        status: "disponivel"
    },
    {
        id: "gw-10",
        nome: "GoodWe Hub - Jundiaí (Anhanguera)",
        lat: -23.2196,
        lng: -46.8971,
        potenciaKw: 120,
        tipo: "DC Fast",
        conectores: ["CCS2", "CHAdeMO"],
        vagasTotal: 4,
        vagasLivre: 0,
        precoKwh: 2.15,
        status: "ocupado"
    },
    {
        id: "gw-11",
        nome: "GoodWe Station - Santos (Ponta da Praia)",
        lat: -23.9856,
        lng: -46.3033,
        potenciaKw: 60,
        tipo: "DC Fast",
        conectores: ["CCS2"],
        vagasTotal: 2,
        vagasLivre: 2,
        precoKwh: 1.95,
        status: "disponivel"
    },
    {
        id: "gw-12",
        nome: "GoodWe Point - São Bernardo (Anchieta)",
        lat: -23.6882,
        lng: -46.5644,
        potenciaKw: 90,
        tipo: "DC Fast",
        conectores: ["CCS2"],
        vagasTotal: 4,
        vagasLivre: 3,
        precoKwh: 2.00,
        status: "disponivel"
    },
    {
        id: "gw-13",
        nome: "GoodWe Hub - Mogi das Cruzes",
        lat: -23.5229,
        lng: -46.188,
        potenciaKw: 60,
        tipo: "DC Fast",
        conectores: ["CCS2"],
        vagasTotal: 2,
        vagasLivre: 1,
        precoKwh: 1.90,
        status: "disponivel",
        horario: [6, 22]
    },
    {
        id: "gw-14",
        nome: "GoodWe Point - Faria Lima",
        lat: -23.5756,
        lng: -46.6887,
        potenciaKw: 22,
        tipo: "AC Wallbox",
        conectores: ["Tipo 2"],
        vagasTotal: 6,
        vagasLivre: 5,
        precoKwh: 1.60,
        status: "disponivel",
        horario: [7, 23]
    },
    {
        id: "gw-15",
        nome: "GoodWe Ultra - Taubaté (Dutra)",
        lat: -23.0543,
        lng: -45.6169,
        potenciaKw: 180,
        tipo: "Ultra Fast",
        conectores: ["CCS2", "Tipo 2"],
        vagasTotal: 6,
        vagasLivre: 6,
        precoKwh: 2.30,
        status: "disponivel"
    },
    {
        id: "gw-16",
        nome: "GoodWe Point - Itu (Bandeirantes)",
        lat: -23.2569,
        lng: -47.2904,
        potenciaKw: 100,
        tipo: "DC Fast",
        conectores: ["CCS2"],
        vagasTotal: 4,
        vagasLivre: 3,
        precoKwh: 2.05,
        status: "disponivel"
    },
    {
        id: "gw-17",
        nome: "GoodWe Point - Vinhedo (Anhanguera)",
        lat: -23.029,
        lng: -46.976,
        potenciaKw: 100,
        tipo: "DC Fast",
        conectores: ["CCS2"],
        vagasTotal: 4,
        vagasLivre: 3,
        precoKwh: 2.10,
        status: "disponivel"
    },
    {
        id: "gw-18",
        nome: "GoodWe Point - Cubatão (Anchieta)",
        lat: -23.895,
        lng: -46.425,
        potenciaKw: 60,
        tipo: "DC Fast",
        conectores: ["CCS2"],
        vagasTotal: 3,
        vagasLivre: 2,
        precoKwh: 1.95,
        status: "disponivel"
    }
];
